# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Duane Cilliers
email: hello@duane.co.za
description: > # this means to ignore newlines until "baseurl:"
  Hello, I'm Duane Cilliers. I've been working on WordPress based projects for 6+ years. In that time I've had the privilege of deploying many projects for clients in various industries. I’m an advocate of best practices, extremely detail-oriented and when I’m not working you will find me expanding my skill set, exploring new technologies or surfing. I absolutely love WordPress and I’m proud to be apart of the thriving community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://duane.co.za" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

sass:
  load_paths:
    - bower_components
